// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTa7obRMkWaWr7Ma4wlAEPieccmHIFZNE',
    appId: '1:968321116168:web:4b1577686db4cd89e749bd',
    messagingSenderId: '968321116168',
    projectId: 'travely-d5c38',
    authDomain: 'travely-d5c38.firebaseapp.com',
    storageBucket: 'travely-d5c38.appspot.com',
    measurementId: 'G-ELVYKG487S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiGQanFXhjlQ5QLTqjrr7OTit6l4W5ZbA',
    appId: '1:968321116168:android:036c953f5eb7bd90e749bd',
    messagingSenderId: '968321116168',
    projectId: 'travely-d5c38',
    storageBucket: 'travely-d5c38.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDdup0w8ivLz20Ibkrjcj5TSgCyEG5kQU',
    appId: '1:968321116168:ios:785237e4b3ad112fe749bd',
    messagingSenderId: '968321116168',
    projectId: 'travely-d5c38',
    storageBucket: 'travely-d5c38.appspot.com',
    iosBundleId: 'com.example.travely',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDdup0w8ivLz20Ibkrjcj5TSgCyEG5kQU',
    appId: '1:968321116168:ios:785237e4b3ad112fe749bd',
    messagingSenderId: '968321116168',
    projectId: 'travely-d5c38',
    storageBucket: 'travely-d5c38.appspot.com',
    iosBundleId: 'com.example.travely',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCTa7obRMkWaWr7Ma4wlAEPieccmHIFZNE',
    appId: '1:968321116168:web:786c9e2ce0c49df2e749bd',
    messagingSenderId: '968321116168',
    projectId: 'travely-d5c38',
    authDomain: 'travely-d5c38.firebaseapp.com',
    storageBucket: 'travely-d5c38.appspot.com',
    measurementId: 'G-0FJ58X0F2S',
  );
}
